fix hacki11/ioBroker.valloxmv#105
hacki11/ioBroker.valloxmv pull request #136
Opened 2022-07-29 21:02 UTC by Feuer-sturm

fix hacki11/ioBroker.valloxmv#105

2022-07-30 03:56 UTC, hacki11 commented
Thank you for your contribution! I will make a release after the findings are handled

2022-07-30 05:43 UTC, Feuer-sturm commented
@hacki11 which findings needs to be handled?

2022-07-30 06:24 UTC, hacki11 commented
See my comments above

2022-07-30 18:15 UTC, Feuer-sturm commented
@hacki11 maybe i'm blind but I can only see this feedback
> Thank you for your contribution! I will make a release after the findings are handled

Where can I find your mentioned findings?

2022-07-30 18:35 UTC, hacki11 commented
https://github.com/hacki11/ioBroker.valloxmv/pull/136/files

2022-07-30 19:11 UTC, Feuer-sturm commented
@hacki11 I am sorry, but this is what I can see:
![grafik](https://user-images.githubusercontent.com/25422320/181944121-82ce8078-bd42-4ced-aa9a-ec6150d73e60.png)


Do you need support from my side?

2022-07-30 19:21 UTC, hacki11 commented
Wenn du in den Tab Filed changed gehst, siehst du da nicht meine Kommentare? Sorry hatte es noch nie, dass das irgendwie versteckt war

2022-07-30 19:27 UTC, Feuer-sturm commented
@hacki11 
Nein ich sehr dort keine Kommentare von dir:
![grafik](https://user-images.githubusercontent.com/25422320/181957667-c0f90c75-4b6e-46ad-a249-d94135c0e2e6.png)


Bei mir kommt es nicht auf ein paar Tage an. Der Adapter läuft bei mir ohne Probleme und steuert meine Lüftungsanlage an :-)

2022-07-31 03:35 UTC, hacki11 requested changes

2022-07-31 11:24 UTC, Feuer-sturm commented on README.md
> -Copyright (c) 2021 hacki11
ok

2022-07-31 12:04 UTC, merged